"""
EPDT Heuristic Algorithm Data Structures

This module defines the core data structures used by the EPDT (Enhanced Parallel 
Diversified Tabu) algorithm for Vehicle Routing Problem with Pickup and Delivery.

These structures are designed to work with the L1 (First-Level) and L2 (Second-Level)
heuristics as described in the EPDT academic paper.

Key Classes:
- Task: Individual pickup or delivery action
- Order: Collection of related pickup and delivery tasks  
- Vehicle: Fleet vehicle with capacity and regulatory constraints
- Route: Sequence of tasks assigned to a vehicle
- Solution: Complete assignment of orders to vehicle routes
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Set, Any
from enum import Enum


class TaskType(Enum):
    """Types of tasks in the VRP."""
    PICKUP = "pickup"
    DELIVERY = "delivery"


@dataclass
class Task:
    """
    Represents an individual pickup or delivery task.
    
    A task is the atomic unit of work in the EPDT algorithm - it represents
    either picking up cargo from a location or delivering cargo to a location.
    """
    id: str
    location_id: str
    task_type: TaskType
    order_id: str  # Which order this task belongs to
    
    # Location and timing
    lat: float
    lon: float
    service_time: float  # Time required to perform the task (minutes)
    
    # Time window constraints
    earliest_time: Optional[float] = None  # Earliest allowed start time (minutes from start)
    latest_time: Optional[float] = None    # Latest allowed start time (minutes from start)
    soft_time_window: bool = False          # Whether time window is soft (allows violations with penalty)
    
    # Cargo information
    demand: float = 0.0      # Cargo weight (kg) - positive for pickup, negative for delivery
    volume: float = 0.0      # Cargo volume (m³) - positive for pickup, negative for delivery
    
    # Task properties
    is_fixed: bool = False   # Whether task position in route can be changed
    priority: int = 1        # Task priority (higher = more important)

    # Day of week constraints
    day: int = 0  # Day of week (0=Today, 1=Tomorrow, -1= Yesterday, etc.)
    
    def is_pickup(self) -> bool:
        """Returns True if this is a pickup task."""
        return self.task_type == TaskType.PICKUP
    
    def is_delivery(self) -> bool:
        """Returns True if this is a delivery task."""
        return self.task_type == TaskType.DELIVERY


@dataclass  
class Order:
    """
    Represents a complete order with pickup and delivery requirements.
    
    An order consists of one or more pickup tasks and one or more delivery tasks.
    The EPDT algorithm ensures precedence constraints: all pickups must occur
    before their corresponding deliveries.
    """
    id: str
    pickup_tasks: List[Task] = field(default_factory=list)
    delivery_tasks: List[Task] = field(default_factory=list)
    
    # Order properties
    priority: int = 1           # Order priority for scheduling
    revenue: float = 0.0        # Revenue generated by completing this order
    is_urgent: bool = False     # Whether this is an urgent order
    is_mandatory: bool = True   # Whether this order must be assigned
    
    # Preferred assignment constraints
    preferred_vehicle_ids: Set[str] = field(default_factory=set)  # Preferred vehicles
    forbidden_vehicle_ids: Set[str] = field(default_factory=set)  # Forbidden vehicles
    
    # Time constraints
    earliest_pickup: Optional[float] = None  # Earliest pickup time across all tasks
    latest_delivery: Optional[float] = None  # Latest delivery time across all tasks
    
    def get_pickups(self) -> List[Task]:
        """Get all pickup tasks for this order."""
        return self.pickup_tasks
    
    def get_deliveries(self) -> List[Task]:
        """Get all delivery tasks for this order."""
        return self.delivery_tasks
    
    def get_all_tasks(self) -> List[Task]:
        """Get all tasks (pickups + deliveries) for this order."""
        return self.pickup_tasks + self.delivery_tasks
    
    def get_total_demand(self) -> float:
        """Get total cargo weight for this order."""
        return sum(task.demand for task in self.pickup_tasks)
    
    def get_total_volume(self) -> float:
        """Get total cargo volume for this order."""
        return sum(task.volume for task in self.pickup_tasks)


@dataclass
class Vehicle:
    """
    Represents a vehicle in the fleet with capacity and regulatory constraints.
    
    This matches the vehicle constraints from the EPDT paper including
    capacity limits, time restrictions, and driver regulation compliance.
    """
    id: str
    depot_id: str
    
    # Capacity constraints
    weight_capacity: float      # Maximum weight capacity (kg)
    volume_capacity: float      # Maximum volume capacity (m³)
    
    # Time and distance constraints  
    max_time: Optional[float] = None       # Maximum route time (minutes)
    max_distance: Optional[float] = None   # Maximum route distance (km)
    
    # Cost parameters
    cost_per_km: float = 1.0              # Cost per kilometer
    cost_per_hour: float = 50.0           # Cost per hour (for break time calculation)
    fixed_cost: float = 0.0               # Fixed cost for using this vehicle
    
    # Vehicle type and capabilities
    vehicle_type: str = "standard"         # "standard" or "heavy" for HOS regulations
    capabilities: Set[str] = field(default_factory=set)  # Special capabilities
    
    # Driver regulation constraints (Hours of Service)
    max_driving_time: float = 540.0        # Max continuous driving (minutes) - 9 hours
    required_break_time: float = 45.0      # Required break duration (minutes)
    max_work_time: float = 780.0           # Max total work time per day (minutes) - 13 hours
    break_frequency: float = 270.0         # Break required every X minutes - 4.5 hours
    
    # Vehicle preferences
    preferred_order_types: Set[str] = field(default_factory=set)  # Preferred order types

    # Loading and unloading constraints
    lifo_required: bool = False  # Last In First Out loading/unloading for vehicles without side doors
    
    # Multi-day planning support
    initial_state: Optional[Dict[str, Any]] = None  # Vehicle's position and pending tasks from previous day


@dataclass
class Route:
    """
    Represents a sequence of tasks assigned to a vehicle.
    
    This is the core data structure for the L2 (Second-Level) heuristic.
    The route maintains the sequence of tasks and provides methods for
    feasibility checking and cost calculation.
    """
    vehicle: Vehicle
    tasks: List[Task] = field(default_factory=list)
    
    # Route metadata
    route_id: Optional[str] = None
    
    # Cached calculations (reset when route changes)
    _cached_score: Optional[float] = field(default=None, init=False)
    _cached_distance: Optional[float] = field(default=None, init=False) 
    _cached_time: Optional[float] = field(default=None, init=False)
    _is_feasible_cached: Optional[bool] = field(default=None, init=False)
    
    def insert_task(self, position: int, task: Task) -> None:
        """Insert a task at the specified position and invalidate caches."""
        self.tasks.insert(position, task)
        self._invalidate_caches()
    
    def remove_task(self, position: int) -> Task:
        """Remove and return the task at the specified position."""
        task = self.tasks.pop(position)
        self._invalidate_caches()
        return task
    
    def swap_tasks(self, pos1: int, pos2: int) -> None:
        """Swap tasks at two positions."""
        self.tasks[pos1], self.tasks[pos2] = self.tasks[pos2], self.tasks[pos1]
        self._invalidate_caches()
    
    def copy(self) -> 'Route':
        """Create a deep copy of this route."""
        import copy
        return copy.deepcopy(self)
    
    def _invalidate_caches(self) -> None:
        """Invalidate all cached calculations."""
        self._cached_score = None
        self._cached_distance = None
        self._cached_time = None
        self._is_feasible_cached = None
    
    def is_feasible(self) -> bool:
        """
        Check if this route is feasible (respects all hard constraints).
        
        This is a placeholder - actual implementation is in second_level.py
        """
        if self._is_feasible_cached is not None:
            return self._is_feasible_cached
        
        # Import here to avoid circular imports
        from .second_level import is_feasible
        self._is_feasible_cached = is_feasible(self)
        return self._is_feasible_cached
    
    def get_orders(self) -> Set[str]:
        """Get set of order IDs in this route."""
        return {task.order_id for task in self.tasks}


@dataclass
class Solution:
    """
    Represents a complete solution to the VRP.
    
    This is the main data structure for the L1 (First-Level) heuristic.
    It maintains the assignment of orders to vehicle routes and tracks
    unassigned orders.
    """
    routes: Dict[str, Route] = field(default_factory=dict)  # vehicle_id -> Route
    unassigned_orders: Set[str] = field(default_factory=set)  # order_ids not assigned
    
    # Solution metadata
    solution_id: Optional[str] = None
    creation_time: Optional[float] = None
    
    # Cached solution-wide calculations
    _cached_z1_score: Optional[float] = field(default=None, init=False)
    
    def add_route(self, vehicle_id: str, route: Route) -> None:
        """Add or update a route for a vehicle."""
        self.routes[vehicle_id] = route
        self._invalidate_caches()
    
    def remove_route(self, vehicle_id: str) -> Optional[Route]:
        """Remove and return the route for a vehicle."""
        route = self.routes.pop(vehicle_id, None)
        if route:
            self._invalidate_caches()
        return route
    
    def assign_order(self, order_id: str, vehicle_id: str) -> None:
        """Assign an order to a vehicle (removes from unassigned)."""
        self.unassigned_orders.discard(order_id)
        self._invalidate_caches()
    
    def unassign_order(self, order_id: str) -> None:
        """Mark an order as unassigned."""
        self.unassigned_orders.add(order_id)
        self._invalidate_caches()
    
    def copy(self) -> 'Solution':
        """Create a deep copy of this solution."""
        import copy
        return copy.deepcopy(self)
    
    def _invalidate_caches(self) -> None:
        """Invalidate cached solution calculations."""
        self._cached_z1_score = None
    
    def get_z1_score(self) -> float:
        """
        Get the Z1 score for this solution.
        
        This is a placeholder - actual implementation is in first_level.py
        """
        if self._cached_z1_score is not None:
            return self._cached_z1_score
        
        # Import here to avoid circular imports
        try:
            from .first_level import calculate_z1_score
            self._cached_z1_score = calculate_z1_score(self)
        except ImportError:
            # Fallback calculation if first_level module not available
            self._cached_z1_score = len(self.get_assigned_orders()) * 100.0
        return self._cached_z1_score
    
    def get_assigned_orders(self) -> Set[str]:
        """Get set of all assigned order IDs."""
        assigned = set()
        for route in self.routes.values():
            assigned.update(route.get_orders())
        return assigned
    
    def get_total_vehicles_used(self) -> int:
        """Get number of vehicles with non-empty routes."""
        return sum(1 for route in self.routes.values() if route.tasks)
    
    def get_vehicle_utilization(self) -> Dict[str, Dict[str, float]]:
        """Get capacity utilization for each vehicle."""
        utilization = {}
        for vehicle_id, route in self.routes.items():
            if not route.tasks:
                utilization[vehicle_id] = {"weight": 0.0, "volume": 0.0}
                continue
                
            # Calculate peak load during route
            current_weight = 0.0
            current_volume = 0.0
            max_weight = 0.0
            max_volume = 0.0
            
            for task in route.tasks:
                current_weight += task.demand
                current_volume += task.volume
                max_weight = max(max_weight, current_weight)
                max_volume = max(max_volume, current_volume)
            
            utilization[vehicle_id] = {
                "weight": max_weight / route.vehicle.weight_capacity,
                "volume": max_volume / route.vehicle.volume_capacity
            }
        
        return utilization


# Algorithm configuration parameters
@dataclass
class EPDTParameters:
    """Configuration parameters for the EPDT algorithm."""
    
    # Tabu Search parameters
    tabu_tenure: int = 10                    # Size of tabu list
    max_non_improving_iterations: int = 50   # M1: Max non-improving iterations
    max_total_iterations: int = 500          # M2: Max total iterations
    
    # Exploration strategy
    exploration_strategy: str = "vnd"        # "vnd" or "cyclic"
    
    # Enhancement flags
    enable_advanced_neighborhoods: bool = True
    enable_granular_search: bool = True
    enable_parallelization: bool = False
    parallel_strategy: str = "PE"            # "PE" (Parallel Evaluation) or "PN" (Parallel Neighborhood)
    
    # Scoring penalties
    vehicle_penalty_per_vehicle: float = 100.0
    unassigned_order_base_penalty: float = 1000.0
    time_window_violation_penalty: float = 50.0
    capacity_violation_penalty: float = 100.0
    
    # Local search parameters
    local_search_strategy: str = "first_improvement"  # "first_improvement" or "best_improvement"
    
    # Initialization method
    initialization_method: str = "best_insertion"     # "best_insertion" or "round_robin"
